// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import ShowbandController from "./showband_controller"
application.register("showband", ShowbandController)

import SwitchController from "./switch_controller"
application.register("switch", SwitchController)
