// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentsController from "./comments_controller"
application.register("comments", CommentsController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import LikeController from "./like_controller"
application.register("like", LikeController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import ShowbandController from "./showband_controller"
application.register("showband", ShowbandController)

import SubmitedController from "./submited_controller"
application.register("submited", SubmitedController)

import SwitchController from "./switch_controller"
application.register("switch", SwitchController)
