AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  IndentationWidth: 2
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/**/*
    - bin/**/*
    - Gemfile
    - Gemfile.lock
    - vendor/**/*
    - config/**/*

Style/Documentation:
  Enabled: false