default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # port: 5432
  # host: localhost
  #username: Joband
  #password:
  database: Joband_development

test:
  <<: *default
  database: Joband_test

production:
  <<: *default
  port: <%= ENV["H_POSTGRES_PORT"] %>
  host: <%= ENV["H_POSTGRES_HOST"] %>
  database: <%= ENV["H_POSTGRES_DB"] %>
  username: <%= ENV["H_POSTGRES_USER"] %>
  password: <%= ENV["H_POSTGRES_PASSWORD"] %>
